spring.application.name=todolist

spring.output.ansi.enabled=always

logging.level.root=info
logging.level.com.bwsy.todolist.mapper=debug
logging.level.org.mybatis=debug
logging.level.java.sql=debug

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=todo
spring.datasource.password=1234

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.bwsy.todolist.dto
mybatis.configuration.map-underscore-to-camel-case=true

# ollama
ollama.base-url=http://localhost:11434
ollama.model=qwen2.5:3b

# .env 파일 읽기
spring.config.import=optional:file:.env[.properties]

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=3600000

# Kakao
oauth.kakao.client-id=${KAKAO_REST_API_KEY}
oauth.kakao.redirect-uri=${KAKAO_REDIRECT_URI}
oauth.kakao.client-secret=${KAKAO_CLIENT_SECRET:}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}