-- system 계정에서 todo라는 이름의 사용자 만들기
CREATE USER todo IDENTIFIED BY "1234";
GRANT DBA TO todo;

-- todo 계정에 접속해서 테이블 생성하기
/* =========================================================
   0. 기존 테이블 삭제
   처음 생성하는 경우에는 실행하지 않아도 됨
   이미 테이블이 있을 때만 아래 순서대로 실행할 것.
   ========================================================= */

DROP TABLE comments CASCADE CONSTRAINTS;
DROP TABLE posts CASCADE CONSTRAINTS;
DROP TABLE todos CASCADE CONSTRAINTS;
DROP TABLE todo_categories CASCADE CONSTRAINTS;
DROP TABLE friends CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;


/* =========================================================
   1. users 테이블
   사용자 정보
   ========================================================= */

CREATE TABLE users (
    user_id NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    email VARCHAR2(100) NOT NULL,
    nickname VARCHAR2(50) NOT NULL,
    provider VARCHAR2(20) NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_nickname UNIQUE (nickname),
    CONSTRAINT chk_users_provider
        CHECK (provider IN ('KAKAO', 'GOOGLE')),
    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'DELETED'))
);


/* =========================================================
   2. todo_categories 테이블
   사용자별 할 일 카테고리
   ========================================================= */

CREATE TABLE todo_categories (
    category_id NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    name VARCHAR2(50) NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_todo_categories_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT uq_todo_categories_user_name
        UNIQUE (user_id, name),
    CONSTRAINT chk_todo_categories_status
        CHECK (status IN ('ACTIVE', 'DELETED'))
);


/* =========================================================
   3. todos 테이블
   할 일 정보
   ========================================================= */

CREATE TABLE todos (
    todo_id NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    category_id NUMBER(19) NOT NULL,
    title VARCHAR2(100) NOT NULL,
    content CLOB,
    todo_date DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'WAITING' NOT NULL,
    priority VARCHAR2(20) DEFAULT 'MEDIUM' NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_todos_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_todos_category
        FOREIGN KEY (category_id)
        REFERENCES todo_categories(category_id),
    CONSTRAINT chk_todos_status
        CHECK (status IN ('WAITING', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT chk_todos_priority
        CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW'))
);


/* =========================================================
   4. friends 테이블
   친구 요청 및 친구 관계
   ========================================================= */

CREATE TABLE friends (
    friend_id NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    requester_id NUMBER(19) NOT NULL,
    receiver_id NUMBER(19) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    responded_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_friends_requester
        FOREIGN KEY (requester_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_friends_receiver
        FOREIGN KEY (receiver_id)
        REFERENCES users(user_id),
    CONSTRAINT chk_friends_not_self
        CHECK (requester_id <> receiver_id),
    CONSTRAINT chk_friends_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DELETED'))
);


/* 같은 두 사용자 간 중복 친구 요청 방지
   A -> B, B -> A 방향이 달라도 중복으로 보지 않기 위한 인덱스 */
CREATE UNIQUE INDEX uq_friends_pair
ON friends (
    LEAST(requester_id, receiver_id),
    GREATEST(requester_id, receiver_id)
);


/* =========================================================
   5. posts 테이블
   커뮤니티 게시글
   ========================================================= */

CREATE TABLE posts (
    post_id NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    title VARCHAR2(150) NOT NULL,
    content CLOB NOT NULL,
    category VARCHAR2(30) NOT NULL,
    view_count NUMBER(10) DEFAULT 0 NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_posts_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT chk_posts_category
        CHECK (category IN ('FREE', 'QUESTION', 'TIP', 'STUDY', 'ERROR')),
    CONSTRAINT chk_posts_status
        CHECK (status IN ('ACTIVE', 'DELETED')),
    CONSTRAINT chk_posts_view_count
        CHECK (view_count >= 0)
);


/* =========================================================
   6. comments 테이블
   게시글 댓글
   ========================================================= */

CREATE TABLE comments (
    comment_id NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    post_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_comments_post
        FOREIGN KEY (post_id)
        REFERENCES posts(post_id),
    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT chk_comments_status
        CHECK (status IN ('ACTIVE', 'DELETED'))
);


/* =========================================================
   7. 조회 성능을 위한 인덱스
   ========================================================= */

CREATE INDEX idx_todo_categories_user
ON todo_categories(user_id);

CREATE INDEX idx_todos_user_date
ON todos(user_id, todo_date);

CREATE INDEX idx_todos_category
ON todos(category_id);

CREATE INDEX idx_friends_requester_status
ON friends(requester_id, status);

CREATE INDEX idx_friends_receiver_status
ON friends(receiver_id, status);

CREATE INDEX idx_posts_user
ON posts(user_id);

CREATE INDEX idx_posts_category_status
ON posts(category, status);

CREATE INDEX idx_comments_post
ON comments(post_id);

CREATE INDEX idx_comments_user
ON comments(user_id);